### ISSUE TITLE
not yet completed

### ISSUE THREAD

**Issue by bboyadao** [TheKalpit/Django-Dynamic-Domains-Tutorial#1]
Please update the code completions as medium's post. Thanks.

**Comment by TheKalpit** [comment]
@bboyadao Can you please share exactly what's incomplete?

**Comment by mcroni** [comment]
hi, how do we go about configuring virtual hosts to make this work, as this is part of the prerequisites

**Comment by TheKalpit** [comment]
@mcroni It is dependent on the server you're using. Please look for tutorials for the same if you're not familiar with it.
